apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-assistant
  namespace: gpu-assistant
  labels:
    app: mathsgpt-gpu
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: Recreate  # Kill old Pod before creating new one, freeing the GPU
  selector:
    matchLabels:
      app: mathsgpt-gpu
  template:
    metadata:
      labels:
        app: mathsgpt-gpu
    spec:
      serviceAccountName: mathsgpt-deployer
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node.kubernetes.io/disk-pressure"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-nodepool: "mathsgpt-gpu-cluster-gpu-pool"
      containers:
        - name: coding-assistant
          image: docker.io/ankitb47/maths-gpt:gpu_v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "4"
              memory: "8Gi"
              nvidia.com/gpu: 1
          env:
            - name: PORT
              value: "8501"
