# coding-assistant/kubernetes/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-assistant
  labels:
    app: mathsgpt-gpu
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mathsgpt-gpu
  template:
    metadata:
      labels:
        app: mathsgpt-gpu
    spec:
      serviceAccountName: mathsgpt-deployer
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
        - name: coding-assistant
          image: docker.io/ankitb47/maths-gpt:gpu_v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8501
          readinessProbe:
            httpGet:
              path: /health
              port: 8501
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
              nvidia.com/gpu: 1
            limits:
              cpu: "4"
              memory: "8Gi"
              nvidia.com/gpu: 1
          env:
            - name: PORT
              value: "8501"