name: Deploy MathsGPT

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image to DockerHub
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/maths-gpt:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/maths-gpt:latest

      - name: SSH to EC2 and deploy latest image
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/maths-gpt || git clone https://github.com/${{ github.repository }} /home/ubuntu/maths-gpt && cd /home/ubuntu/maths-gpt
            git pull
            docker pull ${{ secrets.DOCKER_USERNAME }}/maths-gpt:latest
            docker compose down || true
            docker compose up -d
