name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy-to-cloud-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install & configure gcloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          install_components: beta

      - name: Set GCP project and region
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud config set run/region ${{ secrets.GCP_REGION }}

      - name: Deploy to Cloud Run
        run: |
          gcloud config set run/region ${{ secrets.GCP_REGION }}
          gcloud run deploy maths-gpt \
            --image=docker.io/ankitb47/maths-gpt:cpu_light_optimised \
            --platform managed \
            --service-account=cloud-run-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --port 8501