name: 🚀 Deploy General Assistant

on:
  push:
    branches: [ main ]
    paths:
      - 'general-assistant/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION:     ${{ secrets.GCP_REGION }}
  SA_EMAIL:   cloud-run-deployer@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com

jobs:
  deploy-general:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install gcloud SDK & components
        run: |
          curl -fsSL https://sdk.cloud.google.com | bash >/dev/null
          source $HOME/google-cloud-sdk/path.bash.inc
          # ensure the Cloud Run and GKE auth plugins are available
          gcloud components install beta gke-gcloud-auth-plugin --quiet

      - name: Configure region
        run: |
          gcloud config set project $PROJECT_ID
          gcloud config set run/region $REGION

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy mathsgpt-general \
            --project $PROJECT_ID \
            --region $REGION \
            --platform managed \
            --image docker.io/ankitb47/maths-gpt:general_v1 \
            --port 8501 \
            --cpu 2 --memory 2Gi --concurrency 1 --min-instances 0 \
            --timeout 300s \
            --service-account $SA_EMAIL \
            --allow-unauthenticated
